# ----------------------------------------
# aliases
# ----------------------------------------
alias c="clear"
alias l="ls -l"
if [ $(uname) == "Linux" ]; then
    alias ls="ls --color=auto"
elif
    alias ls="ls -G"
fi
alias ll="ls -l"
alias la="ls -a"
alias .='source'
alias vi='vim'
alias javac="javac -J-Dfile.encoding=utf8"
alias grep="grep --color=auto"


# ----------------------------------------
# envionment variables
# ----------------------------------------
PS1="[\u@\h \w]"\$
