#!/bin/bash

new_file="neededProperties.txt"

if [ $# != 1 ]; then
    echo "Usage: $0 FILENAME"
    echo "eg.: $0 prop.txt"
    exit 1;
fi

if [ ! -f $1 ]; then
    echo "No such file"
    exit 2;
fi

grep ro.product.manufacturer $1 > $new_file
grep ro.product.model $1 >> $new_file
grep ro.product.name $1 >> $new_file
grep ro.board.platform $1 >> $new_file
grep ro.build.version.release $1 >> $new_file
grep ro.build.version.base_os $1 >> $new_file
grep ro.build.version.sdk $1 >> $new_file
grep ro.build.version.incremental $1 >> $new_file
grep ro.build.version.security_patch $1 >> $new_file
grep ro.build.fingerprint $1 >> $new_file
grep ro.build.date.utc $1 >> $new_file
echo "info: " >> $new_file
grep ro.product.brand $1 >> $new_file
grep ro.product.model $1 >> $new_file
